### ISSUE TITLE
MYSQL_SERVICE_DB_PARAM默认值能否改一下

### ISSUE THREAD

**Issue by tky753** [nacos-group/nacos-docker#160]
我看文档里现在**MYSQL_SERVICE_DB_PARAM**的默认值是：
`characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true`
试了老半天死活连不上自定义的mysql，后来看其他文档，手动在docker-compose的environment中改成
```yaml
MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
```
就能连上了
错误提示也不清不楚的，试了老半天才发现问题（发现用environment配置没用，在custom.properties中直接配置连接字符串可以）

**Comment by paderlol** [comment]
我这边试了可以，你怎么配置的

**Comment by tky753** [comment]
我不是很懂mysql，mysql版本用的8.0.22，运行了以下语句
```sql
SELECT @@global.time_zone, @@session.time_zone;
```
返回
'SYSTEM', 'SYSTEM'

所以应该是时区问题，尝试只把  &serverTimezone=UTC 去掉，果然就开不起来了

**Comment by paderlol** [comment]
嗯，我是想问ENV配置你修改不生效这个问题的

**Comment by tky753** [comment]
没用env文件，直接加的environment
env 和 environment 应该是等效的吧

**Comment by tky753** [comment]
我知道我哪里没说清楚了，我不是用的配套的mysql，是连的自己的mysql数据库

**Comment by tky753** [comment]
配套的mysql是可以连的

**Comment by paderlol** [comment]
我知道你用的自定义的库，那个语意是等效的，所以我想看你怎么配置的

**Comment by tky753** [comment]
```yaml
  nacos:
    image: nacos/nacos-server:1.4.1
    container_name: nacos
    restart: always
    environment:
      PREFER_HOST_MODE: ip
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 192.168.0.3
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC  #这句不加上去连不上
    volumes:
      - ~/app/work/nacos/logs/:/home/nacos/logs
      - ~/app/work/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
```
`MYSQL_SERVICE_DB_PARAM: ...`  不加上就连不上

**Comment by paderlol** [comment]
我有点糊涂了，你到底是配置自定义文件生效还是env生效的？

**Comment by tky753** [comment]
一开始我死活连不上，然而windows上的可以连，就把考虑用windows上`application.properties`文件中的推荐的连接字符串试试：
把这几句注释掉
```yaml
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 192.168.0.3
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
```
在custom.properties加上
```
db.url.0=jdbc:mysql://192.168.0.3:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user=nacos
db.password=nacos
```
发现可以，
就仔细观察了一下，发现 你们配置文件的 默认MYSQL_SERVICE_DB_PARAM   和  我在 windows版本的`application.properties`文件中推荐的 连接字符串 有细微不同，
然后又试着不用custom.properties，而在 docker-compose 文件中加上 `MYSQL_SERVICE_DB_PARAM:  ...`，果然就能连上了

于是乎，我就觉得默认的 MYSQL_SERVICE_DB_PARAM   是否也应该改成和windows上`application.properties`文件中的一样？避免很多新手走很多弯路。
