### ISSUE TITLE
swarn 部署 nacos 集群，出现多 leader 情况，并且部分节点无法响应，down 掉的情况

### ISSUE THREAD

**Issue by JarvisPongSky** [nacos-group/nacos-docker#165]
## 问题原因简述

docker stack deploy 部署成功后，查看 nacos 集群注册情况，发现出现多 leader，查看 console log 后没发现错误信息

### cloud-nacos.yml

> 创建网络命令：`docker network create -d overlay --attachable cloud` 

> docker-compose.yml 内容

```yml
version: '3.8' # compose 编排文件版本号
services: # 服务列表

  nacos1: # 服务名称
    image: nacos/nacos-server:1.4.1 # 引用镜像
    hostname: nacos1 # host 名称
    restart: always # 重启策略，docker 启动后，如果有运行此服务会自启
    ports: # 映射端口列表
      - 8841:8848 # 映射 nacos 服务端口
    environment: # 环境参数
      TZ: Asia/Shanghai # 设置上海时区
      PREFER_HOST_MODE: hostname # 支持  hostname 模式
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848 # 集群地址
      MYSQL_SERVICE_HOST: mysql # 数据库连接地址
      MYSQL_SERVICE_DB_NAME: nacos # 数据库库名
      MYSQL_SERVICE_USER: root # 数据库用户名
      MYSQL_SERVICE_PASSWORD: 123456 # 数据库用户密码
    deploy:
      resources:
        limits: # 限制资源
          memory: 2g # 内存容量，支持单位：b、k、m、g
    networks:
      - cloud

  nacos2: # 服务名称
    image: nacos/nacos-server:1.4.1 # 引用镜像
    hostname: nacos2 # host 名称
    restart: always # 重启策略，docker 启动后，如果有运行此服务会自启
    ports: # 映射端口列表
      - 8842:8848 # 映射 nacos 服务端口
    environment: # 环境参数
      TZ: Asia/Shanghai # 设置上海时区
      PREFER_HOST_MODE: hostname # 支持  hostname 模式
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848 # 集群地址
      MYSQL_SERVICE_HOST: mysql # 数据库连接地址
      MYSQL_SERVICE_DB_NAME: nacos # 数据库库名
      MYSQL_SERVICE_USER: root # 数据库用户名
      MYSQL_SERVICE_PASSWORD: 123456 # 数据库用户密码
    deploy:
      resources:
        limits: # 限制资源
          memory: 2g # 内存容量，支持单位：b、k、m、g
    networks:
      - cloud

  nacos3: # 服务名称
    image: nacos/nacos-server:1.4.1 # 引用镜像
    hostname: nacos3 # host 名称
    restart: always # 重启策略，docker 启动后，如果有运行此服务会自启
    ports: # 映射端口列表
      - 8843:8848 # 映射 nacos 服务端口
    environment: # 环境参数
      TZ: Asia/Shanghai # 设置上海时区
      PREFER_HOST_MODE: hostname # 支持  hostname 模式
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848 # 集群地址
      MYSQL_SERVICE_HOST: mysql # 数据库连接地址
      MYSQL_SERVICE_DB_NAME: nacos # 数据库库名
      MYSQL_SERVICE_USER: root # 数据库用户名
      MYSQL_SERVICE_PASSWORD: 123456 # 数据库用户密码
    deploy:
      resources:
        limits: # 限制资源
          memory: 2g # 内存容量，支持单位：b、k、m、g
    networks:
      - cloud


networks:
  cloud:
    external: true # 指定加入外部已存在网络
    name: cloud # 网络名称
```

### 开始部署

> 部署命令：`docker stack deploy -c cloud-nacos.yml cloud_nacos`

### 查看部署情况

部署完成后，查看各节点情况，启动正常。

![image](https://user-images.githubusercontent.com/53456132/109423223-9b1be600-7a19-11eb-9030-a3ead8b6e8b6.png)

查看各节点控制台情况，日志正常。

![image](https://user-images.githubusercontent.com/53456132/109423356-082f7b80-7a1a-11eb-97ed-dee659a1c65d.png)

### 查看 web 集群注册情况

![image](https://user-images.githubusercontent.com/53456132/109423054-0ca76480-7a19-11eb-8d9a-d33111d10807.png)

![image](https://user-images.githubusercontent.com/53456132/109423436-5e9cba00-7a1a-11eb-9bec-a42a95a8a997.png)

![image](https://user-images.githubusercontent.com/53456132/109423454-707e5d00-7a1a-11eb-8ec6-9d11e6069a2f.png)

**查看服务列表，部分节点出现 down 情况**

> nacos 节点1 响应 down

![image](https://user-images.githubusercontent.com/53456132/109423537-c521d800-7a1a-11eb-8528-12b929eb6dfa.png)

> nacos 节点2 成功响应

![image](https://user-images.githubusercontent.com/53456132/109423554-db2f9880-7a1a-11eb-8983-2f33363a5427.png)

> nacos 节点3 响应 down

![image](https://user-images.githubusercontent.com/53456132/109423550-d2d75d80-7a1a-11eb-9c28-09f3471d0882.png)

**回到控制台日志，并无看到错误信息（日志一点都没变化）**

![image](https://user-images.githubusercontent.com/53456132/109423597-03b79280-7a1b-11eb-9ac2-9d0763d3b040.png)
