### ISSUE TITLE
mysql 5.7无法连接

### ISSUE THREAD

**Issue by jianweigit** [nacos-group/nacos-docker#167]
我想在docker容器中使用nacos，并使用单机模式，我本地有mysql容器，而且是5.7版本的， 因为一些特殊原因， 我只能使用5.7版本的
在根据[官方文档](https://nacos.io/zh-cn/docs/quick-start-docker.html)的指引 下载了该项目，
并仿照了example目录下的standalone-mysql-5.7.yaml的文件建立了自己的yml文件，
如下
```yaml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: wei-nacos-standalone
    environment: 
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=172.60.0.2
      - MYSQL_SERVICE_DB_NAME=wei_nacos
      - MYSQL_SERVICE_PORT=10007
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos9423
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "10006:8848"
    restart: on-failure
networks:
  default:
    external:
      name: wei-cooperationassociation
```
### 但是启动报错， 如下：
```sh
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
```
### 然后我在容器中找到服务jar包， 发现mysql的驱动是8.0版本， 如下：
![image](https://user-images.githubusercontent.com/42216997/110941680-b4a32300-8373-11eb-87a4-e3af79861ec6.png)
### 我找到 nacos-all 1.4.1的pom文件， 发现其中 `mysql-connector-java.version` 确实是 8.0.16 ,如下
![image](https://user-images.githubusercontent.com/42216997/110942394-b9b4a200-8374-11eb-9de7-cc3f8fb32de6.png)
