### ISSUE TITLE
三台服务器，分别用docker部署一个nacos,使它们形成集群

### ISSUE THREAD

**Issue by panpengfei21** [nacos-group/nacos-docker#228]
问题如上。
有这样的文档吗？

我把官网的例子改了改
cluster-ip.yml
```
version: "2"
services:
  nacos1:
    image: nacos/nacos-server:1.4.2
    container_name: nacos1
    networks:
      - nacos_net
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    env_file:
      - ../env/nacos-ip.env
    restart: on-failure
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:5.7
    #networks:
    #  nacos_net:
    #    ipv4_address: 172.16.238.13
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
  nacos_net:
    driver: bridge
```

部了一下，发现

localhost:8848连接
```
[root@K8snode1 nacos-docker-master]# nc -vz localhost 8848
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to ::1:8848.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```

局域网IP 不能连接
```
[root@K8snode1 nacos-docker-master]# nc -vz 192.168.0.117 8848
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connection refused.
```
