### ISSUE TITLE
内存限制失败

### ISSUE THREAD

**Issue by baozi-2019** [nacos-group/nacos-docker#270]
现在服务器docker运行nacos:latest镜像直接down掉，原因是nacos把内存吃光了
下面是docker-compose，已经限制最大500m，可是还剩1.5g左右内存都起不来，去掉``memory: 550M``后直接把服务器内存吃光
```yaml
nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - MYSQL_DATABASE_NUM=1
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_dev
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - JVM_XMS=500m
      - JVM_XMX=500m
      - JVM_XMN=300m
    volumes:
      - /opt/docker-file/nacos/logs:/home/nacos/logs
      - /opt/docker-file/nacos/conf/custom.properties:/home/nacos/init.d/custom.properties
    depends_on:
      - mysql
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 550M
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8848/nacos"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5m
```

**Comment by baozi-2019** [comment]
这是没人管了？？？

**Comment by Scorpions777** [comment]
转Consul吧，阿里的kpi开源项目

**Comment by loefun** [comment]
deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 550M
这个内存给的太小了。  实际使用内存 要大于 550M。 这其中包括：-XX:MetaspaceSize

**Comment by wilsonwu** [comment]
```
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi
```

可以参考这个设置会更顺畅运行
