### ISSUE TITLE
Nacos-docker image nacos/nacos-server:2.1.1 No datasource set

### ISSUE THREAD

**Issue by starsoulatnight** [nacos-group/nacos-docker#276]
### 环境：

- Docker

**Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0**

- Linux

**CentOS Linux release 7.9.2009 (Core)**

- nacos镜像：nacos/nacos-server:v2.1.1
- 自定义mysql 版本：8.0.25官方镜像

### 情况：
1.使用下方docker命令启动nacos-mysql8单节点连接自定义数据库失败，报错No datasource set。
```
docker run -itd -p 8848:8848 --name nacos-standalone \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.1.1 \
-e MYSQL_SERVICE_PORT=3306 \
-e MYSQL_SERVICE_ROOT=nacos \
-e MYSQL_SERVICE_PASSWORD=nacos \
-e MYSQL_SERVICE_DB_NAME=nacos_devtest \
-e MYSQL_SERVICE_DB_PARAM='characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai' \
nacos/nacos-server:v2.1.1
```

看了容器中的环境变量，以及application.properties的变量设置均为环境变量，而容器中的环境变量似乎不全。
- 第一怀疑：application.properties中的配置不生效。
- 遂将application.properties的变量全部常量化后，使用该项目readme最下方的自定义配置文件的docker命令：docker run --name nacos-standalone -e MODE=standalone -v /root/application.properties:/home/nacos/conf/application.properties -p 8848:8848  nacos/nacos-server:2.1.1启动。结果仍然：No datasource set

2.使用https://github.com/nacos-group/nacos-docker/blob/master/example/standalone-mysql-8.yaml，该docker-compose的yaml文件是能正常启动nacos-mysql，standalone模式。PS：（但是web页面新增配置，会报错：Publish failed. Make sure parameters are entered correctly），yaml文件如下：
```
version: "2"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql-8
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
```

由于官方yaml能成功，肯定是某个地方出错导致该问题出现。第一怀疑mysql8的版本，官方yaml使用8.0.16，自定义数据库使用mysql8.0.25。做了以下尝试。

- 第一怀疑mysql8的版本，官方yaml使用8.0.16，自定义数据库使用mysql8.0.25。做了以下尝试。
- 将官方yaml启动的mysql容器的数据卷挂载到mysql8.0.25版本的容器mysql-8上，并使mysql-8容器监听宿主机3306端口后，重启nacos-standalone-mysql，能够正常启动。                                     #说明不是版本问题

- 第二怀疑就是自定义的mysql启动命令以及环境变量有问题，做了以下尝试。
- 以官方yaml的mysql部分为基础，修改镜像后部署mysql-8容器，并手动导入初始化脚本（官方yaml的mysql中的初始化脚本也尝试了），创建用户与授权已由于使用环境变量实现了。结果仍然No datasource set

- 第三怀疑就是官方的mysql镜像nacos/nacos-mysql:8.0.16，中的entrypoint.sh脚本做了额外的设置。
- 看了下entrypoint.sh脚本，相比mysql官方镜像少了很多，sql语句也是创建用户然后授权用户远程登陆。

以上情况已排除容器——》数据库的网络问题。已排除数据库账号的权限问题，数据库nacos_devtest初始化使用过官方的sql：https://github.com/alibaba/nacos/blob/develop/distribution/conf/nacos-mysql.sql，数据库nacos初始化也使用过standalone-mysql-8.yaml中使用的mysql镜像里的nacos-mysql.sql，均报错No datasource set

**Comment by starsoulatnight** [comment]
### 新情况：

1. 使用别人给我的application.properties的配置，修改其中的数据库连接地址、账号、密码后，能够使用该配置成功启动nacos/nacos-server:v2.1.1，但是连接的数据库不存储nacos上创建的配置。遂进行下面的尝试

- 使用官方compose的standalone-mysql-8.yaml文件部署单节点mysql存储的两个容器。
根据网友提供的帮助在his_config_info、config_info下创建
enctypted_data_key的字段，即可解决默认yaml构建后无法新建配置的问题。
成功创建配置与命名空间之后，将nacos-standalone-mysql容器删除重建，发现官方用的nacos/nacos-mysql:8.0.16镜像能够成功保存配置到mysql数据库。
然后我将nacos/nacos-mysql:8.0.16的容器删除后，将数据文件挂载到mysql:8.0.25的新容器上，再从nacos上新增配置文件，能够成功存放配置到mysql8.0.25的容器中。

- 上方的操作说明我遇到的“无法存放配置于mysql中”情况与mysql版本没关系，也就没有nacos的mysql驱动问题。遂进行下面的尝试。
删除前面挂载出来的mysql数据文件夹，修改官方standalone-mysql-8.yaml文件，将其中volume部分挂载custom.properties配置文件的地方修改为前面提到的可用配置文件，如下方所示。
```
version: "2"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
##      - /root/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql-8
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
```
（修改config_info、his_config_info表后）结果依然能保存nacos中新建的配置。说明与配置、mysql版本无关，与nacos/nacos-mysql:8.0.16启动的entrypoint脚本所做的事情有关。


头疼，现在毫无头绪了，entrypoint.sh的脚本也看了（实际上没完全懂，只是粗暴的把涉及MYSQL_SERVICE_USER=nacos变量的所有sql语句找出来，判断只是做了创建用户与授权的操作），初始化sql脚本两个镜像用的一致也没用。
