### ISSUE TITLE
docker compose以standalone模式启动，nacos版本号一直显示为0.7.0

### ISSUE THREAD

**Issue by qdlake** [nacos-group/nacos-docker#29]
无论docker的image选择0.9.0，或者1.0.0-RC1，通过浏览器访问，NACOS的版本号一直显示为0.7.0。

![nacos](https://user-images.githubusercontent.com/1879819/55391127-4e98a900-556b-11e9-88d0-855cd0f87feb.png)

```yaml
  nacos:
    image: nacos/nacos-server:0.9.0
    container_name: nacos
    hostname: nacos
    restart: always
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    networks:
      - back-net
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
```
