### ISSUE TITLE
集群模式(启动) Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by xj20305** [nacos-group/nacos-docker#318]
集群模式(启动)
docker-compose -f example/cluster-hostname.yaml up 
报错
Access denied for user 'root'@'localhost' (using password: NO)
环境
Docker Compose version v2.16.0
为什么不适用nacos用户去连接mysql，而用root？

**Comment by xj20305** [comment]
master 和 tagv2.2.0都有这个问题
mysql     [Note] Access denied for user 'root'@'localhost' (using password: NO)
nacos1   INFO Nacos is starting...

**Comment by paderlol** [comment]
一直用的nacos 去连接的
<img width="719" alt="image" src="https://user-images.githubusercontent.com/7919984/226588573-06524619-edf2-4988-a117-138b5a904444.png">

**Comment by paderlol** [comment]
你那个错误是mysql自己的健康检查引起的不用在意

**Comment by geekyouth** [comment]
由于Docker Compose的healthcheck不会自动加载`.env`文件中的环境变量，因此在这种情况下，将环境变量传递给`test`命令会有些困难。解决这个问题的一种方法是将密码直接写入Docker Compose文件，但这样做可能导致安全问题。

另一种方法是创建一个脚本来执行`mysqladmin`命令，并在脚本中使用环境变量。以下是一种可能的解决方案：

1. 创建一个名为`mysql_ping.sh`的脚本文件，内容如下：

```bash
#!/bin/sh
mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}
```

2. 为脚本文件添加可执行权限：

```bash
chmod +x mysql_ping.sh
```

3. 更新Docker Compose文件，将`test`命令更改为运行此脚本：

```yaml
version: '3.8'
services:
  mysql:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_ping.sh:/mysql_ping.sh
    healthcheck:
      test: ["CMD", "/bin/sh", "/mysql_ping.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
```

请注意，这里使用`volumes`选项将`mysql_ping.sh`脚本映射到容器中。通过这种方法，脚本可以访问定义在Docker Compose文件中的环境变量。这将允许脚本使用正确的密码连接到MySQL服务器，避免访问被拒绝的错误。


实测有效
