### ISSUE TITLE
Docker Nacos-server V2.1.1-slim 镜像单机模型启动连接mysql 8.0.3 出现No DataSource set异常

### ISSUE THREAD

**Issue by Abandoner** [nacos-group/nacos-docker#362]
Docker Nacos-server V2.1.1-slim 镜像单机模型启动连接mysql 8.0.3 出现No DataSource set异常, 通过-h 命令连接mysql之后"No DataSource set" 的异常就消失了;

对应mysql的执行命令
mysql -h127.0.0.1 -uroot -p

对应系统 Ubuntu 20.04.1
系统架构 arm64

**Comment by wilsonwu** [comment]
感觉还是网络问题，可以尝试是否能复现？

**Comment by Abandoner** [comment]
> 感觉还是网络问题，可以尝试是否能复现？

应该不是网络问题, 我这边是稳定复现. 多次重启nacos都是无法连接上mysql, 但是使用mysql本身带host的连接命令连接一次之后nacos就可以了.

**Comment by wilsonwu** [comment]
是不是和这个问题有关：https://github.com/alibaba/nacos/issues/10840

**Comment by Abandoner** [comment]
> 是不是和这个问题有关：[alibaba/nacos#10840](https://github.com/alibaba/nacos/issues/10840)

应该不是  mysql我确保了一定比nacos启动的早, 而且mysql完全启动之后如果不执行单独的连接命令的话重启nacos依旧无效

**Comment by wilsonwu** [comment]
了解，我这边还没有遇到过类似问题，或者你尝试使用最新版本的镜像看看是不是也存在问题？

**Comment by Abandoner** [comment]
> 了解，我这边还没有遇到过类似问题，或者你尝试使用最新版本的镜像看看是不是也存在问题？

官网上最新的稳定版本我看到写的是2.1.1 就是用的对应的slim版本, 是不是有新的稳定版本可以使用了?

**Comment by wilsonwu** [comment]
目前最新版本2.2.3，不过2.1.x到2.2.x变化比较大，需要谨慎升级：
<img width="1302" alt="image" src="https://github.com/nacos-group/nacos-docker/assets/1269496/8b28d0bb-48b2-45cc-832d-80ab775cf995">

**Comment by wilsonwu** [comment]
好的，我尝试看看，不过我们用2.1.1的时间比较早，当时也没发现类似问题，目前基本都升级到2.2.3了，目前看还是比较稳定，只能找个环境试试看。

**Comment by Abandoner** [comment]
> 好的，我尝试看看，不过我们用2.1.1的时间比较早，当时也没发现类似问题，目前基本都升级到2.2.3了，目前看还是比较稳定，只能找个环境试试看。

好的  那我最近找时间尝试升级一下nacos试一下 如果解决掉了我马上给您这边反馈一下

**Comment by wilsonwu** [comment]
好的，有问题随时交流。

**Comment by Abandoner** [comment]
```
mysql:
    image: mysql:latest 
    ports:
      - 9527:3306
    environment:
      - MYSQL_ROOT_PASSWORD=transport
      - MYSQL_ROOT_HOST=%
    restart: always
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
      - ./mysql.initdb.d:/docker-entrypoint-initdb.d
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
```

现在发现了解决方法  在mysql的配置中添加了`--default-authentication-plugin=mysql_native_password` 修改默认的认证插件为`mysql_native_password`, 然后nacos就可以直接连上mysql了.至于为什么之前使用host的连接方式连接一下mysql后nacos就可以使用了目前还没有一个很好的解释.
