### ISSUE TITLE
解决No DataSource set的问题，可抄作业

### ISSUE THREAD

**Issue by EminemJK** [nacos-group/nacos-docker#378]
解决No DataSource set的问题，可抄作业：
```
version: "3.0"
services:
# MYSQL
  mysql:
    container_name: mysql
    image: mysql:8.0.26
    volumes:
      - ./saas/mysql/data:/var/lib/mysql
      - ./saas/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./saas/mysql/mysql-files:/var/lib/mysql-files
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
      - LANG=C.UTF-8
      - MYSQL_ROOT_HOST=%
    privileged: true
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
# Nacos
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-standalone-mysql
    environment:
      - TZ=Asia/Shanghai
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    volumes:
      - ./saas/nacos/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
```
