### ISSUE TITLE
k8s使用什么环境变量可以加上nacos.core.auth.enabled=true的鉴权配置

### ISSUE THREAD

**Issue by linjiangyu2** [nacos-group/nacos-docker#412]
目前我使用的k8s资源清单env以下
          env:
            - name: NACOS_REPLICAS
              value: "1"
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MYSQL_SERVICE_DB_NAME
              value: "nacos"
            - name: MYSQL_SERVICE_PORT
              value: "3306"
            - name: MYSQL_SERVICE_USER
              value: "root"
            - name: MYSQL_SERVICE_PASSWORD
              value: "xxxxxxxx"
            - name: MYSQL_SERVICE_HOST
              value: "mysql.base.svc.cluster.local"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: MODE
              value: "standalone"
            - name: NACOS_SERVERS
              value: "nacos.base.svc.cluster.local:8848"
            - name: nacos.naming.data.warmup
              value: "false"
            - name: NACOS_AUTH_ENABLE
              value: "true"
            - name: NACOS_AUTH_TOKEN
              value: "SecretKey012345678901234567890123456789012345678901234567890123456789"
            - name: nacos.core.auth.enable.userAgentAuthWhite
              value: "true"
然后要添加参数nacos.core.auth.enabled=true以开启鉴权功能要怎么添加

**Comment by zx900930** [comment]
用打了补丁的operator+helm chart部署，开启鉴权只需要这些环境变量
```
env:
  - name: NACOS_AUTH_ENABLE
    valueFrom:
      secretKeyRef:
        name: nacos-auth-config
        key: NACOS_AUTH_ENABLE
  - name: NACOS_AUTH_IDENTITY_KEY
    valueFrom:
      secretKeyRef:
        name: nacos-auth-config
        key: NACOS_AUTH_IDENTITY_KEY
  - name: NACOS_AUTH_IDENTITY_VALUE
    valueFrom:
      secretKeyRef:
        name: nacos-auth-config
        key: NACOS_AUTH_IDENTITY_VALUE
  - name: NACOS_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: nacos-auth-config
        key: NACOS_AUTH_TOKEN
```
