### ISSUE TITLE
Docker中单机nacos如何连接单机mysql?

### ISSUE THREAD

**Issue by qq253498229** [nacos-group/nacos-docker#71]
启动不报错，就是页面404连不上
docker-compose.yml:
```
version: "3"
services:
  nacos:
    image: nacos/nacos-server:1.1.4
    container_name: nacos
    volumes:
      - "./config/custom.properties:/home/nacos/init.d/custom.properties"
    env_file:
      - ./config/nacos-hostname.env
    ports:
      - "8848:8848"
      - "9555:9555"
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: nacos
      MYSQL_ROOT_PASSWORD: root
    volumes:
#https://raw.githubusercontent.com/alibaba/nacos/develop/distribution/conf/schema.sql
      - "./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"
```
nacos-hostname.env
```
#nacos dev env
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_DATABASE_NUM=1
MYSQL_MASTER_SERVICE_HOST=mysql
MYSQL_MASTER_SERVICE_PORT=3306
MYSQL_MASTER_SERVICE_DB_NAME=nacos
MYSQL_MASTER_SERVICE_USER=root
MYSQL_MASTER_SERVICE_PASSWORD=root
```
custom.properties:
```
management.endpoints.web.exposure.include=*
```

**Comment by qq253498229** [comment]
启动不报错，就是页面404连不上
```
version: "3"
services:
  nacos:
    image: nacos/nacos-server:1.1.4
    container_name: nacos
    volumes:
      - "./config/custom.properties:/home/nacos/init.d/custom.properties"
      - "./logs:/home/nacos/logs"
    env_file:
      - ./config/nacos-hostname.env
    ports:
      - "8848:8848"
      - "9555:9555"
networks:
  default:
    external:
      name: local
```
nacos-hostname.env
```
#nacos dev env
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_DATABASE_NUM=1
MYSQL_MASTER_SERVICE_HOST=mysql
MYSQL_MASTER_SERVICE_PORT=3306
MYSQL_MASTER_SERVICE_DB_NAME=nacos
MYSQL_MASTER_SERVICE_USER=root
MYSQL_MASTER_SERVICE_PASSWORD=root
```
