### ISSUE TITLE
nacos权限控制功能没生效

### ISSUE THREAD

**Issue by jeraytang** [nacos-group/nacos-docker#93]
用户/角色：nacos/ROLE_ADMIN      dev/ROLE_DEV
权限：ROLE_DEV | dev (4349c029-c625-48e7-bfeb-491b22e30b65) | 读写
设置后dev用户对dev命名空间读写。
使用dev用户登录，左侧权限菜单没了，但是dev用户一样可以查看修改其他命名空间的配置，请教下问题在哪，谢谢！
docker-compose.yml 如下
```
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=地址
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=用户名
      - MYSQL_SERVICE_PASSWORD=密码
    volumes:
      - ./mysql/:/home/nacos/plugins/mysql/
      - /storage/data/nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
    restart: always

```
