### ISSUE TITLE
关于docker-compose脚本mysql配置的一点疑惑

### ISSUE THREAD

**Issue by taneg** [nacos-group/nacos-docker#97]
目前的脚本里面是包含了nacos和mysql的镜像，启一个nacos也就带了个mysql，如果nacos做集群部署，要做到共享数据，mysql是不是要从脚本里面分离出来呢？

**Comment by zw201913** [comment]
我已经把mysql独立出来了，可以参考：https://www.jianshu.com/p/07ad6e817533

**Comment by paderlol** [comment]
本来就可以独立出来啊，我做镜像的目的是为了大家例子使用方便的

**Comment by yuanyunchu** [comment]
> 本来就可以独立出来啊，我做镜像的目的是为了大家例子使用方便的

怎么独立出来呢，我使用docker-compose -f example/standalone-derby.yaml  up -d
添加了mysql8.0显示报错
ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

是我启动方式不对吗，还是用standalone-mysql-8.yaml启动，但是每次启动都会拉取新的镜像
有排除自动拉取mysql8的教程吗

**Comment by paderlol** [comment]
你用mysql8自己的外置链接就要去掉yaml文件里面的数据库的service配置，然后配置你自己的连接就好了

**Comment by yuanyunchu** [comment]
> 你用mysql8自己的外置链接就要去掉yaml文件里面的数据库的service配置，然后配置你自己的连接就好了

##这个是我刚才启动报错的文件standalone-derby.yaml 
```yaml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    - NACOS_AUTH_ENABLE=true
    - SPRING_DATASOURCE_PLATFORM=mysql
    - MYSQL_SERVICE_HOST=xxxx
     # - MYSQL_SERVICE_PORT 默认3306
    - MYSQL_SERVICE_DB_NAME=dmp_conf
    - MYSQL_SERVICE_USER=root
    - MYSQL_SERVICE_PASSWORD=Abcd123#
    - MYSQL_DATABASE_NUM=1

    volumes:
    - ./standalone-logs/:/home/nacos/logs
    - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - "8848:8848"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure


```
*连接的数据库是8.0
* 出现的错误是
```java
rg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configOpsController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.3.0.jar!/com/alibaba/nacos/config/server/controller/ConfigOpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)

```



## 这个是standalone-mysql-8.yaml配置文件
```yaml

version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
```
* 一、我并不知道从哪除去，是否把 mysql:下面全部删除r
* 二、然后是否在nacos-standlone-mysql.env配置数据库信息吗
* 三、我用mysql8的docker启动方式究竟是用那个yaml文件

**Comment by paderlol** [comment]
``` yaml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
## remove those code
 # mysql:
 #   container_name: mysql
 #   image: nacos/nacos-mysql:8.0.16
 #   env_file:
 #     - ../env/mysql.env
 #   volumes:
  #    - ./mysql:/var/lib/mysql
   # ports:
    #  - "3306:3306"
```

**Comment by paderlol** [comment]
``` properties
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST= your host eg 192.168.1.0
MYSQL_SERVICE_DB_NAME=your db name
MYSQL_SERVICE_PORT=db port
MYSQL_SERVICE_USER=db username 
MYSQL_SERVICE_PASSWORD=db password
```

**Comment by yuanyunchu** [comment]
> ```ini
> PREFER_HOST_MODE=hostname
> MODE=standalone
> SPRING_DATASOURCE_PLATFORM=mysql
> MYSQL_SERVICE_HOST= your host eg 192.168.1.0
> MYSQL_SERVICE_DB_NAME=your db name
> MYSQL_SERVICE_PORT=db port
> MYSQL_SERVICE_USER=db username 
> MYSQL_SERVICE_PASSWORD=db password
> ```

是修改nacos-standlone-mysql.env还是nacos-standlone-mysql.env呢

**Comment by paderlol** [comment]
为什么要单独做一个Mysql8的例子,因为Mysql8目前需要自己挂载驱动包的方式,才能使用.
``` yaml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
    # mysql properties here
      - ../env/nacos-standlone-mysql.env
    volumes:
        # here mysql plugin for db driver
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
```

然后自己使用外置数据库请手动先初始化数据库脚本,数据库脚本在nacos官方项目下面可以找到,**[传送门](https://github.com/alibaba/nacos/blob/develop/distribution/conf/nacos-mysql.sql)**

**Comment by paderlol** [comment]
nacos-standlone-mysql.env

**Comment by yuanyunchu** [comment]
> 为什么要单独做一个Mysql8的例子,因为Mysql8目前需要自己挂载驱动包的方式,才能使用.
> 
> ```yaml
> version: "2"
> services:
>   nacos:
>     image: nacos/nacos-server:latest
>     container_name: nacos-standalone-mysql
>     env_file:
>     # mysql properties here
>       - ../env/nacos-standlone-mysql.env
>     volumes:
>         # here mysql plugin for db driver
>       - ./plugins/mysql/:/home/nacos/plugins/mysql/
> ```
> 
> 然后自己使用外置数据库请手动先初始化数据库脚本,数据库脚本在nacos官方项目下面可以找到,**[传送门](https://github.com/alibaba/nacos/blob/develop/distribution/conf/nacos-mysql.sql)**

* 公司的情况只能是在他们现有的数据库操作，我也不想这样搞，直接官网教程简单多了o(╥﹏╥)o

**Comment by paderlol** [comment]
所以你只需要移除mysql服务就好了,然后直接配置外部地址

**Comment by yuanyunchu** [comment]
> 所以你只需要移除mysql服务就好了,然后直接配置外部地址

我刚刚按照你的配置来配了 .但启动了还是报错
##  错误信息
```yml
ConfigOpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)


```

*   standalone-mysql-8.yaml文件
```yaml
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
        #    - ./standalone-logs/:/home/nacos/logs
        #  - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
        #  ports:
            #   - "8848:8848"
        #   - "9555:9555"
        #   depends_on:
            #  - mysql
            #    restart: on-failure
    #  mysql:
    # container_name: mysql
    # image: nacos/nacos-mysql:8.0.16
    # env_file:
    # - ../env/mysql.env
    # volumes:
    #   - ./mysql:/var/lib/mysql
    # ports:
    # - "3306:3306"

```   
* nacos-standlone-mysql.env配置
```yaml
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=172.16.xx.11
MYSQL_SERVICE_DB_NAME=dmp_conf
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=Abcd123#
~                                 

```
被这个问题搞了一天┭┮﹏┭┮

**Comment by paderlol** [comment]
第一、172.16.xx.11 这个ip是连的上吗？ 看着像私有Ip 你得用配置外网ip.
第二、/plugins/mysql/目录下有没有配置你们的mysql8的驱动.
第三、数据库脚本有没有初始化.

**Comment by paderlol** [comment]
配置文件是这样的
``` yaml
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./standalone-logs/:/home/nacos/logs
       - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
      ports:
           - "8848:8848"
           - "9555:9555"
      restart: on-failure
```
